export interface Data {
    id: string,
    firstName: string,
    lastName: string,
    email: string,
    phone: string,
    street: string,
    houseNo: number,
    city: string,
    postalCode: number,
    linkToDSGVO: string,
    createdBy: string,
}

export const data: Data[] = [
    {
        id: "1",
        firstName: "Max",
        lastName: "Mustermann",
        email: "mäxchentest@gmail.com",
        phone: "+401627364738",
        street: "Kielstr",
        houseNo: 3,
        city: "Lüneburg",
        postalCode: 21337,
        linkToDSGVO: "url2",
        createdBy: "Raphaela",
    },
    {
        id: "",
        firstName: "Karl",
        lastName: "Schreiber",
        email: "a@gmail.com",
        phone: "+40162dsf7338",
        street: "Streetname",
        houseNo: 9,
        city: "Hamburg",
        postalCode: 23476,
        linkToDSGVO: "url3",
        createdBy: "Raphaela",
    },
]