export interface Data {
    id: string,
    firstName: string,
    lastName: string,
    email: string,
    phone: string,
    street: string,
    houseNo: number,
    city: string,
    postalCode: number,
    linkToDSGVO: string,
    createdBy: string,
}

export const data: Data[] = [
    {
        id: "1",
        firstName: "Max",
        lastName: "Mustermann",
        email: "mäxchentest@gmail.com",
        phone: "+401627364738",
        street: "Straßenname",
        houseNo: 5,
        city: "Mustercity",
        postalCode: 23456,
        linkToDSGVO: "url",
        createdBy: "Raphaela",
    },
    {
        id: "3",
        firstName: "Karl",
        lastName: "Schreiber",
        email: "aschbautest@gmail.com",
        phone: "+401627364738",
        street: "Straßenname",
        houseNo: 5,
        city: "Mustercity",
        postalCode: 23456,
        linkToDSGVO: "url",
        createdBy: "Raphaela",
    },
    {
        id: "4",
        firstName: "Andrea",
        lastName: "Müller",
        email: "aschbautest@gmail.com",
        phone: "+401627364738",
        street: "Straßenname",
        houseNo: 5,
        city: "Mustercity",
        postalCode: 23456,
        linkToDSGVO: "url",
        createdBy: "Raphaela",
    },
    {
        id: "5",
        firstName: "Paul",
        lastName: "Aschbau",
        email: "aschbautest@gmail.com",
        phone: "+401627364738",
        street: "Straßenname",
        houseNo: 5,
        city: "Mustercity",
        postalCode: 23456,
        linkToDSGVO: "url",
        createdBy: "Raphaela",
    },
    {
        id: "6",
        firstName: "Mimi",
        lastName: "Aschbau",
        email: "aschbautest@gmail.com",
        phone: "+401627364738",
        street: "Straßenname",
        houseNo: 5,
        city: "Mustercity",
        postalCode: 23456,
        linkToDSGVO: "url",
        createdBy: "Raphaela",
    },
    {
        id: "2",
        firstName: "Anna",
        lastName: "Aschbau",
        email: "aschbautest@gmail.com",
        phone: "+401627364738",
        street: "Straßenname",
        houseNo: 5,
        city: "Mustercity",
        postalCode: 23456,
        linkToDSGVO: "url",
        createdBy: "Raphaela",
    },
]